title: My Boring First Github page
author: Boring Byte
email: boringbyte@github.com
description: > # this means to ignore newlines until "baseurl:"
  The never thought I would have this much of patience in learning
  tricks about github. I would just stick to by git add, commit, clone,
  pull commands. Nothing fancy or complicated. But something changed my
  mind.

# social links
twitter_username: nope # DO NOT include the @ character, or else the build will fail!
github_username:  boringbyte # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
